input.onButtonPressed(Button.A, function () {
    control.reset()
    basic.showNumber(game.score())
})
input.onPinPressed(TouchPin.P1, function () {
    game.addScore(1)
    basic.showNumber(game.score())
})
game.setScore(0)
basic.showNumber(game.score())
basic.forever(function () {
    basic.showNumber(game.score())
    if (game.score() == 6) {
        control.reset()
        basic.showNumber(game.score())
    }
})
basic.forever(function () {
    music.playTone(659, music.beat(BeatFraction.Whole))
    basic.pause(500)
    music.playTone(622, music.beat(BeatFraction.Quarter))
    basic.pause(100)
    music.playTone(659, music.beat(BeatFraction.Whole))
    basic.pause(500)
    music.playTone(622, music.beat(BeatFraction.Quarter))
    basic.pause(100)
    music.playTone(659, music.beat(BeatFraction.Whole))
    music.playTone(622, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Whole))
    music.playTone(784, music.beat(BeatFraction.Double))
    basic.pause(500)
    music.playTone(659, music.beat(BeatFraction.Whole))
    basic.pause(500)
    music.playTone(622, music.beat(BeatFraction.Quarter))
    basic.pause(100)
    music.playTone(659, music.beat(BeatFraction.Whole))
    basic.pause(500)
    music.playTone(622, music.beat(BeatFraction.Quarter))
    basic.pause(100)
    music.playTone(659, music.beat(BeatFraction.Whole))
    music.playTone(622, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Whole))
    music.playTone(587, music.beat(BeatFraction.Double))
    basic.pause(100)
    music.playTone(659, music.beat(BeatFraction.Whole))
    basic.pause(500)
    music.playTone(622, music.beat(BeatFraction.Quarter))
    basic.pause(100)
    music.playTone(659, music.beat(BeatFraction.Whole))
    basic.pause(500)
    music.playTone(622, music.beat(BeatFraction.Quarter))
    basic.pause(100)
    music.playTone(659, music.beat(BeatFraction.Whole))
    music.playTone(622, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Whole))
    music.playTone(880, music.beat(BeatFraction.Double))
    basic.pause(100)
    basic.pause(500)
})
